dependencies:
- ipywidgets==8.1.7
- PyYAML==6.0.3
- requests==2.32.5
- numpy==2.3.5
- pandas==2.3.3
- matplotlib==3.10.8
- scikit-image==0.26.0
- scipy==1.16.3
- statsmodels==0.14.6
- scikit-learn==1.8.0
- seaborn==0.13.2
- umap-learn==0.5.11
description: This notebook 'AFT_tracks_last_version.ipynb' is for ...
python_version: 3.14.2
